### ISSUE TITLE
ENOENT: no such file or directory, lstat 'node_modules/@teamhanko/frontend-sdk'

### ISSUE THREAD

**Issue by IgnisDa** [teamhanko/hanko#521]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

I am trying to install `@teamhanko/frontend-sdk` in my project using `yarn`. But I am getting:

![image](https://user-images.githubusercontent.com/60938164/214755951-4e119298-a551-48ec-82de-896c5ceb2cd1.png)

### Reproducing the bug

Simply run `yarn install @teamhanko/hanko-elements`

### Hanko Version

v0.3.2

### OS

Linux

### Environment

None

### Additional Context

It is probably due to this line https://github.com/teamhanko/hanko/blob/5da32426e324f2405d78361f9436055a1eaa42c3/frontend/elements/package.json#L73.

**Comment by like-a-bause** [comment]
The fronted-sdk should be bundled into the hanko-elements package. We'll take a look. Thanks for the report!

**Comment by like-a-bause** [comment]
I can reproduce this with yarn v1.22.19 and the error:
```
error Package "" refers to a non-existing file '"/private/tmp/frontend-sdk"'.
```
Maybe our setup here isn't optimal. We could try to handle the dependency with workspaces? https://docs.npmjs.com/cli/v7/using-npm/workspaces

**Comment by IgnisDa** [comment]
indeed this should be solved using workspaces. Maybe something like turborepo?

**Comment by pistachiomatt** [comment]
1 month later and still an issue? I can confirm that a stock-standard fresh repo install with Yarn will fail. Pretty major!

**Comment by like-a-bause** [comment]
On the linked branch(feat-monorepo) we are currently evaluating how development within a monorepo/workspace context could work. Once this is functional we'll dump the file reference.
